### ISSUE TITLE
Documentation has gone missing

### ISSUE THREAD

**Issue by zapotah** [lsyncd/lsyncd#649]
https://axkibe.github.io/lsyncd/ gives a 404 error.

**Comment by zmfdan** [comment]
Yeah:
![page-not-found-2021-11-29 16-58-24](https://user-images.githubusercontent.com/86930681/143891121-cc8d4b74-6984-4244-8578-d263f2b47db8.png)
h

**Comment by zmfdan** [comment]
Workaround: https://web.archive.org/web/20211011093128/https://axkibe.github.io/lsyncd/

**Comment by jaroslawhartman** [comment]
Unfortunately, this project is slowly dying 😞 Think twice before using it in any production environment.

**Comment by poelzi** [comment]
I will fix this soon

**Comment by poelzi** [comment]
The new docs are at https://lsyncd.github.io/lsyncd/

**Comment by poelzi** [comment]
I updated the README. I think that github does not create a proper redirect when the project is moved

**Comment by TheLinuxNinja** [comment]
There are hosting providers like LiquidWeb that rely on this software for syncing load-balanced front-end servers. Please don't let it die.

**Comment by axkibe** [comment]
I added "<meta http-equiv="refresh" content="0; URL=https://lsyncd.github.io/lsyncd/">" forwardes to all pages of the old manual to forward to it's new home at lsyncd/lsyncd (instead of axkibe)  (except of the manual in the making of the v3 stump I was writing that never came to be)

**Comment by poelzi** [comment]
fixed
