### ISSUE TITLE
Daemon startup failed

### ISSUE THREAD

**Issue by Huyueeer** [lsyncd/lsyncd#651]
I don't understand. I want to establish real-time synchronization. After configuring `nodaemon = false`, the following words will appear when starting. After testing, I found that `nodaemon = true` can be started. Is it my omission?
![image](https://user-images.githubusercontent.com/40758588/149283086-9a597e03-aba6-4fa0-9596-88b3c51e058b.png)
``` luc
settings {
	logfile ="/tmp/lsyncd.log",
	statusFile ="/tmp/lsyncd.status",
	inotifyMode = "CloseWrite",
	maxProcesses = 10,
	maxDelays = 1 ,
	statusInterval = 5,
	nodaemon = false,
}
sync{
	default.rsync,
	source="/file1",
	target="/file2",
	delay = 15,
	rsync = {
		binary = "/usr/bin/rsync",
		archive = true,
		compress = true
	}
}
```

**Comment by LeonGaultier** [comment]
Is the issues described still present?
