### ISSUE TITLE
rsync not working in two way lsyncd configuration

### ISSUE THREAD

**Issue by PrajaktaReke123** [lsyncd/lsyncd#666]
Hello,  I have configured lsyncd on 2 servers. below is the lsyncd config file settings for both servers:  

for server 1: rsync setting:
source= server1
destination= server 2

and for server 2 setting is vice versa:
source= server2
destination= server1

rsync works perfectly on server 1, immediately reflects new changes on server2, though it has a different user and permission on the same folder.
on the second server rsunc only works when I run lsyncd confing file. command : sudo service lsyncd status -l. 
 rsync does not work for server2, changes are not reflected immediately on server1. Can anyone help me out with this? Here is my lsync config setting:
**server1:**

-- lsyncd config file for 2-way sync
settings {
logfile = "/var/log/lsyncd/lsyncd.log",
statusFile = "/var/log/lsyncd/lsyncd.status",
statusInterval = 1,
nodaemon = true,
insist = true
}
sync {
default.rsync,
source = "path/uploads",
target = "bitnami@<IP_server2>:/path/uploads",
delete = 'running',
--delay = 5,
rsync = {
-- timeout = 3000,
update = true,
times = true,
archive = true,
compress = true,
perms = true,
acls = true,
owner = true,
rsh = "<ssh_key>"
}
}

**server 2**:
settings {
logfile = "/var/log/lsyncd/lsyncd.log",
statusFile = "/var/log/lsyncd/lsyncd.status",
statusInterval = 1,
nodaemon = true,
insist = true
}
sync {
default.rsync,
source = "path/uploads",
target = "bitnami@<IP_server1>:/path/uploads",
delete = 'running',
--delay = 5,
rsync = {
-- timeout = 3000,
update = true,
times = true,
archive = true,
compress = true,
perms = true,
acls = true,
owner = true,
rsh = "<ssh_key>"
}
}
Please help

**Comment by poelzi** [comment]
Lsync has to run on both machines. Lsync is not a 2 way sync tool, but reactor to local changes, by doing something. Normally copy the file to remote host.
If you sync one directory to server2 and the same directory from server2 into server1 as a source, you are bound for trouble. In fact, that is the best way to ensure data corruption. You can have one directory to write date into that is the master to write into and sync this to the other server. You could then unify this somehow.
Shared, synced, multi writeable directories is the hardest FS problem there is. You have to do conflict resolution and other very hard problem. Maybe git-annex or some other tool is of more use for your case, but lsync can't do this.
