### ISSUE TITLE
how to filter exclude folder？

### ISSUE THREAD

**Issue by season886** [lsyncd/lsyncd#677]
```
 exclude = {
       'node_modules/**',
       'data/**',
       'log/**',
       'tmp/**'
    }
```
How to exclude folders like "log/**" but filter special folders "vendor/log" ?

**Comment by MarviMcFly** [comment]
It depends on what you are trying to achieve. I would recommend to have a look in the official documentation (https://lsyncd.github.io/lsyncd/manual/config/layer4/) while this is not in issue but more an help request.

What I cloud imagine is to define special additional `sync` definition which only handle the by you needed special folders. 

In example: You will exclude `log` with `**` globally (as you did) and define a new sync with `source = vendor/log`.

According to the documentation it may be applicable for you to replace `log/**` with `/log/**`

> - Generally if any segment of the pathname (see below Layer 3) of an event matches the text, it is excluded. E.g. the file “/bin/foo/bar” matches the rule “foo”.
- If the rule starts with a slash, it will only be matched at the beginning of the pathname
- If the rule ends with a slash, it will only be matched at the end of a pathname
- ? matches any character that is not a slash.
- * matches zero or more characters that are not a slash
- ** matches zero or more characters, this can be slashes.

Hope this somehow helps.
