### ISSUE TITLE
How to setup bidirectionnel syncing btw 2 folders ?

### ISSUE THREAD

**Issue by jumpingjackgazz** [lsyncd/lsyncd#690]
Hi there,

I'm quite new to lsyncd but so far I can not find any .lua sample providing a bidirectionnal syncing of 2 local folders...
Let's say, I have 2 directories (/home/user/rep1 and /home/user/rep2) on the same server, and I'd like to have a two-way sync, i.e. any update /home/user/rep1 is reflected in /home/user/rep2 and vice-versa.

Can someone help on this one ?
Thx

**Comment by poelzi** [comment]
Since your question pops up from time to time I clarified the readme. bidirectional sync is better done with tools like syncthings or git-annex. It might work with lsync, but your chances for corruption depends highly on your use case and configuration.
