### ISSUE TITLE
Normal, Retrying Move

### ISSUE THREAD

**Issue by invizus** [lsyncd/lsyncd#692]
Hello. I have an issue which occurs randomly, it can happen once in a few months, or few times a month. The cause is unknown. Normally I would restart lsyncd daemon but wondering if anyone knows what could be the issue?

```
lsyncd: Normal, Retrying Move /srv/source/uploads//test/515125125.pdf: 255
```

lsyncd 2.1.6-1 on Debian 9. Latest version available on this distro, so cannot upgrade further without migrating to new distro.

The service itself is running as normal. After I restart the service, files get synced to destination without any issue.

In the meantime, is it possible to configure lsyncd to fail when this occurs, then I could configure systemd unit to restart on failure, so hat I do not have to intervene manually.

Thank you.

**Comment by poelzi** [comment]
Please post your configuration, so I can take a look.
In normal operations, failed operations will be retried automatically, until success or a hard timeout.
So, retrying is a good thing and should result in the successful synchronization of the affected file. Is the file not synced correctly ?
