### ISSUE TITLE
lsyncd ignoring sqlite database with rsyncssh

### ISSUE THREAD

**Issue by hhartzer** [lsyncd/lsyncd#700]
I'm testing out using lsyncd to sync a sqlite database with rsyncssh. It syncs fine on startup, and will rsync new files in the directory, but if the sqlite file is changed, it never gets sent over until lsyncd is restarted.

Is this an inotify issue? I'm not really sure what's going on.

Thanks!!

**Comment by poelzi** [comment]
By default, lsyncd listens to close after write events, when a program holds the file open and never closes it, the event is not triggered. There i a option to change this.
Syncing databases that are under usage is very dangerous and might end in corruption. The safest way to do it, is to use something like sqlite to create a dump file and sync this file. This can be done with a hook. Or locking the file while sync is running, but this is blocking.

**Comment by hhartzer** [comment]
Thank you! Is that inotifyMode = modify?

My understanding is that sqlite is ACID complaint and so the disk state should always be steady, even if a change is incomplete. I may be mistaken, though.

I could also try to make a dump file as I go, but I was hoping to sync the live file.

**Comment by poelzi** [comment]
This is not what ACID means. ACID are properties of the user facing side and usually implemented using journals and in file updates. When your journal file is not exact version your main file is, stuff breaks. I'm just telling you, don't do it, might work many times, but then it doesn't.

**Comment by hhartzer** [comment]
Thank you! That makes sense. I appreciate your time.

**Comment by poelzi** [comment]
Please not that that you can use lsyncd for this very well, but you need to dump the file and transfer the dump instead.
Something like `sqlite3 file.sqlite .dump > /tmp/file.sql`
You can get inspired by https://github.com/lsyncd/lsyncd/blob/master/examples/limagemagic.lua how to implement this.
