### ISSUE TITLE
SSH option incorrectly parsed

### ISSUE THREAD

**Issue by Forbinn** [lsyncd/lsyncd#716]
Hi, I run into an issue when using lsyncd with the ssh config.

First here is the relevant part of the config:

```
    ssh          = {
        identityFile = "/root/.ssh/id_rsa_lsyncd",
        options      = { "CheckHostIP=yes", "IdentitiesOnly=yes", "StrictHostKeyChecking=yes" },
        port         = 22
    }
```

But when I run I get an error and the rsync command looks weird:
```
18:08:40 Exec: rsync [-ltvXnxsACp] [--bwlimit=5MiB] [--rsh=ssh -i /root/.ssh/id_rsa_lsyncd -o 1=CheckHostIP=yes -o 2=IdentitiesOnly=yes -o 3=StrictHostKeyChecking=yes -p 22] [-r] [/tmp] [lsyncd@storage:/]
```

As you can see the options of the SSH commands starts with the index in the table from the config. I was unable to find a configuration online that uses this fields and I'm not an expert in lua so it may just be my mistake.

**Comment by axkibe** [comment]
It's a long time, but I think you are supposed to use it like this:
```
options  = { CheckHostIP="yes", IdentitiesOnly="yes", StrictHostKeyChecking="yes" }
```
Note the different quotes, you provided a list of strings, instead a table of strings.

**Comment by Forbinn** [comment]
And you are right now it works perfectly. Sorry for the dumb issue and thank you for the quick response.
