### ISSUE TITLE
`inotifyMode` only for a specific sync

### ISSUE THREAD

**Issue by brauliobo** [lsyncd/lsyncd#729]
Hi! I've tried changing `inotifyMode` only for one sync, but it seems it changed for all other `sync` blocks, as the lsyncd CPU usage increased significantly. Here is the config file I've used:
```
sync {
  default.rsync,
  source  = '/mnt/4tb',
  exclude = { '.snapshots' },
  target  = 'root@target:/mnt/4tb',
  --delete  = 'running',
  delay   = 60,
  settings {
    inotifyMode = 'CloseWrite or Modify',
  },
  rsync   = {
    _extra = {'--temp-dir=/srv/tmp', '-axP'},
    update = true,
    archive = true, --implies times, perms, acls, owner
  }
}
```

Is this the correct way?

**Comment by axkibe** [comment]
It's a global setting by design because there is only one inotify engine which assigns the events to the syncs.

**Comment by brauliobo** [comment]
ok, thanks for the answer @axkibe

**Comment by brauliobo** [comment]
I've started a new hobby project to replace lsyncd with roots in more performant concepts, check out https://github.com/brauliobo/ruby-livesync?tab=readme-ov-file#key-features
